# -*- coding: utf-8 -*-
"""CS464 MadaweeAlabdulkreem_443012689.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mXt1VAH7_j6VaQSCXKVfUx9OlWCA-kVG

#**Medical Image Classification Using Convolutional Neural Networks (CNNs)**

* Madawee Alabdulkreem

# **1- Environment Setup**

### **Library Installation**
"""

import sys
print(sys.version)

!pip install -U scikit-learn==1.5.2

!pip install scikeras==0.13.0 --upgrade

!pip install opendatasets

"""### **GPU Cheack**
 Cheack GPU if it's available or not, if not Activative it
"""

!nvidia-smi

import torch

if torch.cuda.is_available():
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
    print(f"GPU Is Available: {torch.cuda.is_available()}")
else:
    print("GPU is not available.")

def num_gpus():
    """Get the number of available GPUs."""
    return torch.cuda.device_count()

num_gpus()

"""# **2- HAM10000 DataSet**

### **Dowmload dataset**
Dowmload Skin Cancer MNIST: HAM10000 Dataset from Kaggle directly using API Token
"""

import opendatasets as od
od.download('https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000')

import os
data_dir = "./skin-cancer-mnist-ham10000"
os.listdir(data_dir)

import pandas as pd
import numpy as np
np.random.seed(42)
metadata_path = os.path.join(data_dir, "HAM10000_metadata.csv")
ham_dataset = pd.read_csv(metadata_path)

"""# **3- Data Exploration and Preprocessing**
Display dataset (metadata.csv) to understand its structure and features, The HAM10000 dataset contain 10015 row and 7 columns, it's contain 7 catagories:

-	nv: Melanocytic nevi
-	mel: Melanoma
-	bkl: Benign keratosis-like lesions
-	bcc: Basal cell carcinoma
-	acliec: Actinic keratoses
-	vas: Vascular lesions
-	df: Dermatofibroma

I read "The HAM10000 dataset: a large collection of multi-source dermatoscopic images  of common pigmented skin lesions" to understand the dataset and its classes.
"""

ham_dataset

"""note that in the first two row we have the same (lesion id) but a diffrent image id"""

classes = np.unique(ham_dataset['dx'])
nClasses = len(classes)

print("Number of classes:", nClasses)
print(classes)

# Checking for null and other info
ham_dataset.info()

"""#### **Map each imge_id with its image file to make it easier in the next operations.**"""

from glob import glob
all_images = glob(os.path.join(data_dir, "HAM10000_images_part_*", "*.jpg"))
image_path = {os.path.splitext(os.path.basename(x))[0]: x for x in all_images}
print("img num::", len(all_images))

"""#### **Resizing images (64*64)**

"""

from PIL import Image
#Define the path and add as a new column
ham_dataset['path'] = ham_dataset['image_id'].map(image_path.get)
#Use the path to read images.
ham_dataset['image'] = ham_dataset['path'].map(lambda x: np.asarray(Image.open(x).resize((64,64))))

"""add path and image into the coulmns"""

ham_dataset

"""#### **Cheack for missing data**

"""

print("Dataset shape:", ham_dataset.shape)

print("\nMissing values:")
print(ham_dataset.isnull().sum())

"""age has null values so wee need to get rid of them or we can ignore it"""

#drop rows with missing values and duplicates
ham_dataset = ham_dataset.dropna()
ham_dataset = ham_dataset.drop_duplicates(subset='image_id')

print("\nMissing values:")
print(ham_dataset.isnull().sum())

"""#### **Data Visualization**

Visualize the categories (dx) balance
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 5))
sns.countplot(x='dx', data=ham_dataset)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""We can see the data is unbalanced"""

#Check how many in each one
ham_dataset['dx'].value_counts()

"""as we can see the classes are imbalanced, **nv** contain **6660** while **df** contain **115** and that's a big difference that will effect on the results

#### **Display some of the data**
"""

n_samples = 1
categories = ham_dataset['dx'].unique()

fig, axes = plt.subplots(1, len(categories), figsize=(20, 4))

for ax, category in zip(axes, categories):
    sample = ham_dataset[ham_dataset['dx'] == category].sample(1, random_state=1234)
    img = sample.iloc[0]['image']

    ax.imshow(img)
    ax.set_title(category)
    ax.axis('off')

plt.tight_layout()
plt.show()

"""# **4-Split of Data**

Check for Duplicate Lesions
"""

# get number of non-unique lesion_id's
def check_duplicates(df, col):
    unique_list = df.lesion_id.unique().tolist()
    num_duplicates = len(df) - len(unique_list)
    return num_duplicates

num_duplicates = check_duplicates(ham_dataset, 'lesion_id')
print(f'Duplicate lesion_ids: {num_duplicates} out of {len(ham_dataset)}')

"""Split the Dataset based on lesion id"""

from sklearn.model_selection import train_test_split

unique_lesions = ham_dataset['lesion_id'].unique()

# Splite the dataset based on 'lesion_id' intp train - test - validation 70:15:15
train_lesions, temp_lesions = train_test_split(unique_lesions, test_size=0.30, random_state=42)
val_lesions, test_lesions = train_test_split(temp_lesions, test_size=0.50, random_state=42)

#DataFrames
train_df = ham_dataset[ham_dataset['lesion_id'].isin(train_lesions)]
val_df   = ham_dataset[ham_dataset['lesion_id'].isin(val_lesions)]
test_df  = ham_dataset[ham_dataset['lesion_id'].isin(test_lesions)]

print("Train:", len(train_df))
print("Val:", len(val_df))
print("Test:", len(test_df))

"""Check for overlapping lesions between train, validation, and test sets

"""

overlap_train_val = set(train_df['lesion_id']).intersection(set(val_df['lesion_id']))
overlap_train_test = set(train_df['lesion_id']).intersection(set(test_df['lesion_id']))
overlap_val_test = set(val_df['lesion_id']).intersection(set(test_df['lesion_id']))

print("Overlap train-val:", len(overlap_train_val))
print("Overlap train-test:", len(overlap_train_test))
print("Overlap val-test:", len(overlap_val_test))

"""Save train/val/test splits to CSV and reload them

"""

train_df.to_csv("train_split.csv", index=False)
val_df.to_csv("val_split.csv", index=False)
test_df.to_csv("test_split.csv", index=False)

train_df = pd.read_csv("train_split.csv")
val_df = pd.read_csv("val_split.csv")
test_df = pd.read_csv("test_split.csv")

train_df

"""Cheack for data imbalnce again for the train to apply data agumentation"""

train_df['dx'].value_counts()

val_df

test_df

"""#### **Normalization**
Load, resize, normalize images and handle errors by adding a blank image if loading fails

"""

from tqdm import tqdm

def load_normalize_images(df, target_size=(64, 64)):
    images = []
    for path in tqdm(df['path']):
        try:
            # Load image
            img = Image.open(path)
            # Resize if needed
            if img.size != target_size:
                img = img.resize(target_size)
            # Convert to array and normalize to [0, 1]
            img_array = np.array(img).astype('float32') / 255.0
            # Ensure 3 channels (convert RGBA to RGB if needed)
            if len(img_array.shape) == 3 and img_array.shape[-1] == 4:
                img_array = img_array[:, :, :3]
            images.append(img_array)
        except Exception as e:
            print(f"Error loading image {path}: {e}")
            # Add a normalized blank image
            images.append(np.zeros((*target_size, 3), dtype='float32'))

    return np.array(images)

# Load and normalize images
X_train = load_normalize_images(train_df)
X_val = load_normalize_images(val_df)
X_test = load_normalize_images(test_df)

print(f"shape: {X_train.shape}")
print(f"after normalization: [{X_train.min():.3f}, {X_train.max():.3f}]")

"""#### **Encoding Class Labels**
Encode class labels (dx) as integers and convert to one-hot vectors for model training

"""

from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# Encode labels
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(train_df['dx'])
y_val_encoded = label_encoder.transform(val_df['dx'])
y_test_encoded = label_encoder.transform(test_df['dx'])

# Convert to categorical (one-hot encoding)
y_train = to_categorical(y_train_encoded, num_classes=nClasses)
y_val = to_categorical(y_val_encoded, num_classes=nClasses)
y_test = to_categorical(y_test_encoded, num_classes=nClasses)

X_train

y_train

# Verify the normalization worked correctly
print(f"X_train shape: {X_train.shape}") # (num_samples, 64, 64, 3)
print(f"X_train dtype: {X_train.dtype}")
print(f"X_train range: [{X_train.min():.3f}, {X_train.max():.3f}]")

print(y_train.shape)  # (num_samples, nClasses)

"""#### **Data Agumentaion**
To balance training set, increase samples per class to target_count using ImageDataGenerator to all class except (nv)

"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import pandas as pd
from tqdm import tqdm

# add 2000 to each class
target_count = 2000
#Data Agumentation
train_datagen = ImageDataGenerator(
    rotation_range=15,     # rotate ±15°
    width_shift_range=0.1, # shift horizontally ±10%
    height_shift_range=0.1,# shift vertically ±10%
    horizontal_flip=True,  # flip horizontally
    vertical_flip=True,    # flip vertically
    zoom_range=0.1,        # zoom ±10%
    shear_range=0.1,       # shear ±10%
    fill_mode='nearest'    # fill empty pixels with nearest
)

augmented_images = []
augmented_labels = []

# Apply in all class except ( nv )
for cls in train_df['dx'].unique():
    cls_indices = train_df[train_df['dx'] == cls].index
    X_cls = X_train[cls_indices]
    y_cls = y_train[cls_indices]

    n_samples = X_cls.shape[0]

    if n_samples >= target_count:
        # don't include nv
        X_final = X_cls
        y_final = y_cls
    else:
        n_needed = target_count - n_samples
        aug_iter = train_datagen.flow(X_cls, y_cls, batch_size=1, shuffle=True)

        X_aug, y_aug = [], []

        for _ in tqdm(range(n_needed)):
            X_batch, y_batch = next(aug_iter)
            X_aug.append(X_batch[0])
            y_aug.append(y_batch[0])

        X_final = np.concatenate([X_cls, np.array(X_aug)], axis=0)
        y_final = np.concatenate([y_cls, np.array(y_aug)], axis=0)

    augmented_images.append(X_final)
    augmented_labels.append(y_final)

# marge them
X_train_final = np.concatenate(augmented_images, axis=0)
y_train_final = np.concatenate(augmented_labels, axis=0)

print(f"\Training set shape: {X_train_final.shape}, {y_train_final.shape}")


y_labels = np.argmax(y_train_final, axis=1)
class_names = label_encoder.inverse_transform(y_labels)
class_distribution = pd.Series(class_names).value_counts()

print("\nafter augmentation:")
print(class_distribution)

X_train_final.shape
y_train_final.shape

"""# **5- Model architecture**

## Here is the custom CNN architectue I used

- **6 Conv layers** (32/64 filters, 3x3 & 5x5, ReLU) tried tanh but the relu was better
- **BatchNorm** and **Dropout**(0.25) tried two value 0.25 and 0.5 to avoid overfitting
- **Pooling** i tried bot MaxPooling and avgpooling the max was better
- **Flatten** :Dense(300,100, ReLU) + Dropout
- **Output** Dense(num_classes, softmax)
- **Optimizer**: AdamW also here tried Adam, SGD and AdamW
- **Loss**: categorical_crossentropy
- **Metric**: accuracy
"""

# From A Convolutional Neural Network Approach for Skin Lesion Classification Using Imbalanced Dataset with Image Augmentation
from tensorflow import keras
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization,AveragePooling2D
from tensorflow.keras.layers import Activation
from tensorflow.keras.optimizers import AdamW


# Input size (64*64)
def create_model(learning_rate=1e-4,weight_decay=1e-5, input_shape=(64, 64, 3), num_classes=7):
    model = Sequential()

    #Convolutional layer 1 (32*32) - Filter size (3*3) - Activation Function (Relu)
    model.add(Conv2D(32, (3, 3), padding="same", activation='relu', input_shape=input_shape))
    model.add(BatchNormalization())
    model.add(Dropout(0.25))
    model.add(MaxPooling2D(2, 2))

    #Convolutional layer 2 (32*32) - Filter size (3*3) - Activation Function (Relu) - Dropout to avoid the overfitting
    model.add(Conv2D(32, (3, 3), padding="same",activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.25))
    model.add(MaxPooling2D(2, 2))

    #Convolutional layer 3 (32*32) - Filter size (5*5) - Activation Function (Relu) - Dropout to avoid the overfitting
    model.add(Conv2D(32, (5, 5), padding="same", activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.25))

    #Convolutional layer 4 (64*64) - Filter size (3*3) - Activation Function (Relu) - Dropout to avoid the overfitting
    model.add(Conv2D(64, (3, 3), padding="same", activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.25))
    model.add(MaxPooling2D(2, 2))

    #Convolutional layer 5 (64*64) - Filter size (3*3) - Activation Function (Relu) - Dropout to avoid the overfitting
    model.add(Conv2D(64, (3, 3), padding="same", activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.25))

    #Convolutional layer 6 (64*64) - Filter size (5*5) - Activation Function (Relu)
    model.add(Conv2D(64, (5, 5), padding="same", activation='relu'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(2, 2))


    #Flatten the input
    model.add(Flatten())

    #Fully connected layers
    model.add(Dense(300, activation='relu'))
    model.add(Dense(100, activation='relu'))
    model.add(Dropout(0.25))
    model.add(Dense(num_classes, activation='softmax')) #output

    #tried both Adam and AdamW and AdamW was better
    optimizer = AdamW(learning_rate=learning_rate, weight_decay=weight_decay)
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

    return model

"""# **6-Hyper-parameters Tuning with K-Folds** - RUN-ONES
- K-Folds: Use 3-fold cross-validation (KFold) to evaluate different hyper-parameter combinations, i used 5 too but it's get hevey on my laptop

- GridSearchCV tests batch_size, epochs, and learning_rate to find the best configuration.

- ModelCheckpoint saves the model

- EarlyStopping stops training if val_loss does not improve for 10 epochs and restores best weights.

- After fitting, print the best score and parameters along with mean/std for each combination.

"""

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

from sklearn.model_selection import KFold
# Define the crossvalidation process to be used inside cross_val_score evaluation
cv = KFold(n_splits=3, random_state=42, shuffle=True)

#Parameter grid
param_grid = {
    'batch_size': [16, 32],
    'epochs': [10,20],
    'model__learning_rate': [1e-4, 5e-4, 1e-3],
}


checkpoint = ModelCheckpoint(
    'BestLast_one_6_skin_lesion_model3.keras',
    monitor='val_loss',
    save_best_only=True,
    mode='min',
    verbose=1
)

# Define early stopping callback
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True,
    verbose=1
)


#from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from scikeras.wrappers import KerasClassifier

model = KerasClassifier(
    model=create_model,
    verbose=1
)

from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=cv)
grid_result = grid.fit(
    X_train_final, y_train_final,
    validation_data=(X_val, y_val),
    callbacks=[early_stopping, checkpoint]
)

print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']

for mean, stdev, param in zip(means, stds, params):
    print(f"{mean:.6f} ({stdev:.6f}) with: {param}")

"""# **7- Training**
 - Take the best hyper-parameters from GridSearchCV results.
- Train model with data augmentation and early stopping.
- Save best model using ModelCheckpoint.
- Print total number of epochs completed.
- print the test accurecy

"""

# Get the best parameters found during GridSearch
best_params = grid_result.best_params_
print(best_params)

# Create the final model using the best learning rate (default = 1e-4 if not found)
final_model = create_model(
    learning_rate=best_params.get('model__learning_rate', 1e-4),
)

epochs = 30
# Train the model with data augmentation and best parameters
history = final_model.fit(train_datagen.flow(X_train_final, y_train_final, batch_size=best_params.get('batch_size')),
                          epochs=epochs,
                           validation_data=(X_val, y_val),
                           callbacks=[early_stopping, checkpoint],
                           verbose=1)


print(f"Training stopped at epoch {len(history.history['loss'])}")

"""## **Save the model**
save it in google drive to reuse it anytime
"""

from google.colab import drive
drive.mount('/content/drive')

final_model.save('/content/drive/MyDrive/BestLast_one_6_skin_lesion_model3.keras')

"""##**Model Performance Evaluation**"""

from tensorflow.keras.models import load_model

best_model_3 = load_model('BestLast_one_6_skin_lesion_model3.keras')
test_loss3, test_accuracy3  = best_model_3.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {100*test_accuracy3:.4f}")

"""## **Accuracy and Loss Visualization**"""

#Accuracy
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training vs Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

# Loss
plt.figure(figsize=(8,5))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training vs Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

"""***NOTE:*** that this is one of the models that i train but the best one is in output section and for the validation and train in the documantaion

# **8- Import Best Model**

#### **Load The best model**
"""

from tensorflow.keras.models import load_model
from google.colab import drive

drive.mount('/content/drive')

model = load_model("/content/drive/MyDrive/Best_Model_DlMid.keras")

""" ## **Model's Summary**
 provides a detailed of the model architecture, including the types of layers, their output shapes, and the total number of trainable parameters.
"""

model.summary()

optimizer_config = model.optimizer.get_config()
print(optimizer_config)

"""## **Test Accurecy**"""

test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {100*test_accuracy:.4f}")

"""## **Confusion Matrix**"""

#Predict on test
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.argmax(y_test, axis=1)

# display confuison matrix
cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap='Blues', values_format='d')
plt.title("Confusion Matrix")
plt.show()

"""## **Classification Report**
display for each class precision, recall and f1-score
"""

classes = ['akiec', 'bcc', 'bkl', 'df', 'mel', 'nv', 'vasc']

report = classification_report(y_true, y_pred, target_names=classes, digits=3)
print("Classification Report:\n")
print(report)

"""# **Outout (Predict)**
use the trained model to predict a random test image. The image is displayed with its true label, and the model outputs the predicted class along with the confidence scores for all possible classes.
"""

# take random photo from test ( new one the model did not see)
idx = np.random.randint(0, len(X_test))
sample_img = X_test[idx]
true_label = np.argmax(y_test[idx])

plt.imshow(sample_img)
# display the true label
plt.title(f"True Label: {classes[true_label]}")
plt.axis("off")
plt.show()

#predict
pred_probs = model.predict(np.expand_dims(sample_img, axis=0))
pred_label = np.argmax(pred_probs)

# see the probabilities for each class
print("Probabilities:")
for label, prob in zip(classes, pred_probs[0]):
    print(f"{label}: {prob:.4f}")

#based on propabilty the model will take highest value and predict based on it
print(f"\nPredicted Class: {classes[pred_label]} (confidence = {pred_probs[0][pred_label]:.2f})")